app/models.py
from flask import url_for
from flask_sqlalchemy import SQLAlchemy
from flask import url_for

db = SQLAlchemy()

class Book(db.Model):
    __tablename__ = 'books'
    id = db.Column(db.Integer, primary_key=True)
    pages = db.Column(db.Integer,  nullable=True)
    title = db.Column(db.String(250))
    description = db.Column(db.String(1000), nullable=True)
    cover = db.Column(db.String(250), nullable=True)

    def __str__(self):
        return f"{self.name}"

    @property
    def cover_url(self):
        return url_for('static', filename=f'books/images/{self.cover}')

    @property
    def show_url(self):
        return url_for('books.show', id=self.id)

    @property
    def delete_url(self):
        return url_for('books.delete', id=self.id)

    @property
    def edit_url(self):
        return url_for('books.edit', id=self.id)

app/books/forms.py
from flask import Flask, render_template, redirect, url_for
from flask_bootstrap import Bootstrap5

from flask_wtf import FlaskForm, CSRFProtect
from wtforms import StringField, SubmitField, IntegerField, FileField
from wtforms.validators import DataRequired, Length

class BookForm(FlaskForm):
    title = StringField('What is the Title of the book?', validators=[DataRequired(), Length(10, 250)])
    cover = FileField('Add here the Cover image')
    description = StringField('Add a brief Description about the book ')
    pages = IntegerField ('How many Pages?', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap5
from flask_migrate import migrate, Migrate

from app.config import config_options
from app.models import db


def create_app (config_name='prod'):
    app = Flask(__name__)
    current_config = config_options[config_name]
    app.config.from_object(current_config)
    app.config['SQLALCHEMY_DATABASE_URI'] = current_config.SQLALCHEMY_DATABASE_URI

    db.init_app(app)

    migrate = Migrate(app, db)

    bootstrap = Bootstrap5(app)

    from app.books import book_blueprint
    app.register_blueprint(book_blueprint)









    return app

app/books/__init__.py
from flask import Blueprint


book_blueprint = Blueprint('books', __name__, url_prefix='/books')

from app.books import views

app/books/views.py
from flask import request, render_template, url_for, redirect
from werkzeug.utils import secure_filename

from app.books import book_blueprint
from app.models import Book, db
import os



@book_blueprint.route('', endpoint='index')
def index():
    books = Book.query.all()
    return render_template("books/index.html", books=books)



@book_blueprint.route('<int:id>/show', endpoint='show')
def show (id):
    book = db.get_or_404(Book, id)
    return render_template("books/show.html", book=book)

@book_blueprint.route('/<int:id>/delete', endpoint='delete')
def delete(id):
    book = db.get_or_404(Book, id)
    db.session.delete(book)
    db.session.commit()
    return redirect(url_for('books.index'))

# forms
from app.books.forms import BookForm
@book_blueprint.route("/create", endpoint='create', methods=["GET", "POST"])
def create():
    form = BookForm()
    if request.method=="POST":
        if form.validate_on_submit():
            cover_name = None
            if request.files.get('cover'):
                cover = form.cover.data
                cover_name = secure_filename(cover.filename)
                cover.save(os.path.join('static/books/images', cover_name))
            data= dict(request.form)
            del data['csrf_token']
            del data['submit']
            data['cover'] = cover_name
            book = Book(**data)
            db.session.add(book)
            db.session.commit()
            return redirect(book.show_url)
    return render_template('books/forms/create.html', form=form)

@book_blueprint.route('/<int:id>/edit', endpoint='edit', methods=['GET', 'POST'])
def edit(id):
    # get all books first
    book = Book.query.get_or_404(id)
    form = BookForm(obj=book)
    if request.method == "POST":
        if form.validate_on_submit():
            book.title = form.title.data
            book.description = form.description.data
            book.pages = form.pages.data
            if request.files.get('cover'):
                cover = form.cover.data
                cover_name = secure_filename(cover.filename)
                cover.save(os.path.join('static/books/images', cover_name))
                book.cover = cover_name
            db.session.commit()
            return redirect(book.show_url)

    return render_template('books/forms/edit.html', form=form, book=book)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}Library App{% endblock %}</title>
</head>
<body>
  <div class="container mt-4">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4" aria-label="Main navigation">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('books.index') }}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('books.index') }}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('books.create') }}" class="btn btn-primary">Add a New Book</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Content -->
    <div class="content">
        {% block content %}
        <p>Welcome to my app!</p>
        {% endblock %}
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

app/templates/books/create.html
{% extends 'base.html' %}

{% block content %}
<h1>Add a New Book</h1>
<form method="POST">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title" required>
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
    </div>
    <div class="form-group">
        <label for="cover">Cover Photo</label>
        <input type="text" class="form-control" id="cover" name="cover" required>
    </div>
    <div class="form-group">
        <label for="pages">pages</label>
        <input type="text" class="form-control" id="pages" name="pages" required>
    </div>
    <button type="submit" class="btn btn-info mt-3">Submit</button>
</form>

{% endblock %}

app/templates/books/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit Book</h1>
<form method="POST">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title" value="{{ book.title }}" required>
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" name="description" rows="3" required>{{ book.description }}</textarea>
    </div>
    <div class="form-group">
        <label for="cover">Image</label>
        <input type="text" class="form-control" id="cover" name="cover" value="{{ book.cover }}" required>
    </div>
    <button type="submit" class="btn btn-info mt-3">Submit</button>
</form>
<a href="{{ url_for('books') }}" class="btn btn-info mt-3">Back to Home</a>
{% endblock %}

app/templates/books/forms/create.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
Edit Book
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">

      <h1 class="pt-5 pb-2">Edit Book</h1>

      {{ render_form(form) }}

      <p class="pt-5"><strong>{{ message }}</strong></p>

    </div>
  </div>
</div>

{% endblock %}

app/templates/books/forms/edit.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
Library
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-lg-auto mx-md-auto">

      <h1 class="pt-5 pb-2">Welcome to Library App</h1>

      {{ render_form(form) }}

      <p class="pt-5"><strong>{{ message }}</strong></p>

    </div>
  </div>
</div>

{% endblock %}

app/templates/books/index.html
{% extends './base.html' %}
{% block content %}
    <h1>Welcome to BooksS</h1>
    <h2>{{ title }}</h2>

    <div class="row">
        {% for book in books %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img src="{{ book.cover_url }}" class="card-img-top" alt="Image for {{ book.title }}" style="height: 200px; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">{{  book.title }}</h5>
                        <p class="card-text">{{ book.description }}</p>
                        <a href="{{book.show_url}}" class="btn btn-info">Show</a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/books/show.html
{% extends './base.html' %}

{% block content %}

<h4>Post Info</h4>
<div class="card" style="width: 18rem;">
  <img src="{{book.cover_url}}" class="card-img-top" alt="{{ book['title'] }}">

  <div class="card-body">
    <h5 class="card-title">{{ book['title'] }}</h5>
    <p class="card-text">{{ book['description'] }}</p>
    <div><a href="{{book.edit_url}}" class="btn btn-info">Edit</a>
    <a href="{{book.delete_url}}" class="btn btn-danger">Delete</a></div>
    <div><a href="{{ url_for('books.index') }}" class="btn btn-primary">Back to All Books</a></div>
  </div>
</div>

{% endblock %}

app/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
<div >
  <img style="margin: auto" src="{{url_for('static', filename='errors/error.jpeg')}}">
  <a href="{{ url_for('posts') }}">Return to Home</a>

</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" ></script>

</body>
</html>